In [16]:
import numpy as np

# 3.1
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)
print(arr *4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print("min: " + str(np.argmin(arr)) + " max: " + str(np.argmax(arr)))
print(arr[np.argmin(arr)], arr[np.argmax(arr)])
print(np.min(arr), np.max(arr))
print(arr[arr > 20]) # w boolean indexing!

# 3.2
matrix = np.array([
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
])
print(np.shape(matrix))
print(np.shape(matrix)[0]) # columns
print(np.shape(matrix)[1]) # rows
# indexes as (rows, columns)
print(matrix[:, 2]) # third column 
print(matrix[1]) # second row
print(matrix * 2)
print(np.mean(matrix, axis = 0)) # row, but vertically
print(np.mean(matrix))
print(np.max(matrix, axis = 1)) # column, but horizontally
print(np.min(matrix, axis = 0))
flat = matrix.flatten()
print(flat) # makes it all in one dimension, row 1 + row 2 + row...
print(flat.shape) #should be js one dimension so it is how many in that row. 
print(np.min(flat), np.max(flat))
print(np.unravel_index(np.argmin(flat), matrix.shape))
print(np.unravel_index(np.argmax(flat), matrix.shape))
print(matrix[matrix > 15])
print(np.sort(matrix))

# 4
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def isPrime(num):
    for i in range(num):
        if num % (i+1) == 0:
            return False
        return True

def primeRows(arr):
    result = np.array([])
    for row in arr:
        primeInRow = False
        for i in row:
            if isPrime(i):
                primeInRow = True
        if primeInRow:
            np.append(result, row, axis = 0)

print(primeRows(arr))

# 5.1
def zeros():
    zeros = np.zeros((8, 8))
    return zeros
    
def checkerboard():
    board = zeros()
    board[::2, ::2] = 1
    board[1::2, 1::2] = 1
    return board

def reverseCheckerboard():
    board = zeros()
    board[::2, 1::2] = 1
    board[1::2, ::2] = 1
    return board

# 6
def expansion(arr, n):
    expanded_words = []
    for word in arr:
        expanded = ""
        for i in range(len(word)):
            expanded += word[i]
            if i != len(word) - 1:
                expanded += " " * n
        expanded_words.append(expanded)
    return np.array(expanded_words)


# 7
def secondBrightest(arr):
    second = []
    for row in arr:
        brightest = float('-inf')
        second_brightest = float('-inf')
        for star in row:
            if star > brightest:
                second_brightest = brightest
                brightest = star
            elif star > second_brightest and star != brightest:
                second_brightest = star
        second.append(second_brightest)
    return np.array(second)


[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
min: 6 max: 7
4 50
4 50
[27 31 50 39 35]
(3, 4)
3
4
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)
3 21
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]
None
